package bigip

const (
	uriLtm                   = "ltm"
	uriNode                  = "node"
	uriPool                  = "pool"
	uriPoolMember            = "members"
	uriProfile               = "profile"
	uriServerSSL             = "server-ssl"
	uriClientSSL             = "client-ssl"
	uriProfileHttp           = "http"
	uriPersistences          = "persistences"
	uriPersistenceCookie     = "cookie"
	uriPersistenceSourceAddr = "source-addr"
	uriPersistenceHash       = "hash"
	uriProfileTCP            = "tcp"
	uriProfileFTP            = "ftp"
	uriProfileUDP            = "udp"
	uriProfileFastL4         = "fastl4"
	uriOneConnect            = "one-connect"
	uriVirtual               = "virtual"
	uriVirtualAddress        = "virtual-address"
	uriSnatPool              = "snatpool"
	uriMonitor               = "monitor"
	uriIRule                 = "rule"
	uriPolicy                = "policy"
	uriDatagroup             = "data-group"
	uriInternal              = "internal"
	ENABLED                  = "enable"
	DISABLED                 = "disable"
	CONTEXT_SERVER           = "serverside"
	CONTEXT_CLIENT           = "clientside"
	CONTEXT_ALL              = "all"
)
